--- # Set-up WordPress dependencies

- name: Download WordPress
  get_url:
    url: http://wordpress.org/wordpress-{{ wp_version }}.tar.gz
    dest: /tmp/wordpress-{{ wp_version }}.tar.gz
    checksum: "sha256:{{ wp_sha256sum }}"

- name: Extract archive
  unarchive:
    src: /tmp/wordpress-{{ wp_version }}.tar.gz
    dest: "{{ wp_document_root | dirname }}"
    remote_src: yes

- name: Get random salts
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt
    return_content: yes
  register: wp_salts

- name: Copy WordPress config file
  template:
    src: wp-config.php.j2
    dest: "{{ wp_document_root }}/wp-config.php"
  notify:
    - "harden web root"
    - restart web service
