---

- name: Create WordPress Database
  mysql_db:
    name: "{{ wp_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci
- name: Create WordPress DB User
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present