---

- name: Enable firewall port rules
  ufw:
    state: enabled
    rule: allow
    proto: tcp
    port: "{{ item }}"
  with_items:
    - 22
    - 80
    - 443

- name: Disable any other incoming traffic
  ufw:
    state: enabled
    default: deny

